### ISSUE TITLE
Running on linux failed

### ISSUE THREAD

**Issue by nik9000** [SBBTracker/SBBTracker#42]
I downloaded `SBBTracker-v3.10.0` this morning and untared it and ran it and go this error:
```
$ ./bin/SBBTracker 
Traceback (most recent call last):
  File "application.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "asset_utils.py", line 12, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/manybubbles/Downloads/tmp/SBBTracker-v3.10.0/bin/../assets/template-ids.json'
[1687] Failed to execute script 'application' due to unhandled exception!
```

I got past that by running:
```
rsync -a assets/assets/* assets/
```

Now I'm seeing:
```
$ ./bin/SBBTracker 
Traceback (most recent call last):
  File "application.py", line 49, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "graphs.py", line 7, in <module>
  File "matplotlib/__init__.py", line 1144, in use
  File "matplotlib/pyplot.py", line 267, in switch_backend
  File "matplotlib/pyplot.py", line 268, in backend_mod
  File "importlib/__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt5agg'
[2737] Failed to execute script 'application' due to unhandled exception!
```

It looks like you intend for all of the dependencies to be bundled but this one doesn't seem to be. A global install for that dependency doesn't get me past this either.

**Comment by andrewrasch** [comment]
Apologies, I don't check the builds on linux very often (I should really make a vm for this). I'm looking into the problem now.

**Comment by andrewrasch** [comment]
Alright I just reuploaded the v3.10.0 linux release. Should work now (although the overlay doesn't seem to work, I'll have to fix that in a later release)
